version: '3'
services:
  app:
    image: golang:alpine
    container_name: tax-calculator
    build: .
    command: go run main.go
    volumes:
      - .:/go/src/tax-calculator
    working_dir: /go/src/tax-calculator
    ports:
     - "9090:9090"